[package]
name = "game-music-emu"
version = "0.1.0"
authors = ["Jay Pavlina <jay@explodingrabbit.com>"]
edition = "2018"
#links = "gme"
build = "build.rs"

#[lib]
#crate-type = ["cdylib"]

[dependencies]
#cpal = "0.8.2"
#rodio = "0.8.1"
libc = "0.2.50"

[build-dependencies]
cc = "1.0"