[package]
name = "game-music-emu"
version = "0.1.0"
authors = ["Jay Pavlina <jaypavlina@gmail.com>"]
edition = "2018"
build = "build.rs"

[features]
default = ["ay", "gbs", "gym", "hes", "kss", "nsf", "nsfe", "sap", "spc", "vgm",]
ay = []
gbs = []
gym = []
hes = []
kss = []
nsf = []
nsfe = []
sap = []
spc = []
vgm = []

#[lib]
#crate-type = ["cdylib"]

[dependencies]
libc = "0.2"

[build-dependencies]
cc = "1.0"